name: places
description: Sufr flutter education

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.1
  dart_code_metrics: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.1


flutter:
  assets:
    - res/images/
    - res/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Bold.ttf
        - asset: res/fonts/Roboto-Italic.ttf
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-Medium.ttf
  uses-material-design: true


